### PR TITLE
New icons.

### PR DESCRIPTION
**Pull request by jwakely**
I tried replacing the icons with more realistic lantern images as I wanted something a bit less blocky, but the 19x19 one is too small to really see anything, so I don't think they are an improvement over your originals! 

Just close this pull request if you don't like them. I'll probably try to create something simpler in a drawing program, rather than a scaled down photograph that loses all the detail.

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
What about removing some details from the smaller one?

**Comment by newfolder0** [comment]
Hey! Thanks for the suggestions! I have been offered new icons by at least three or four different people so I'll have to sit down and choose one as soon as I have time. I'm having a very busy week and the little spare time I do have is going into fixing the bugs and trying to optimise the functional stuff. I'll get back to you this weekend, thank you very much again for your input!

**Comment by newfolder0** [comment]
So, the options that currently stand are:
1. The icon in this pull request: https://raw.githubusercontent.com/jwakely/chrome-clacks/527a10c8cfe104ff1ecac224c736a3525f92dd68/src/images/icon38.png
2. A vector icon (easily scalable) sent to me by a guy who has asked to be credited as Sap1ens: https://drive.google.com/file/d/0B8ibwb8Ve2lUTE1RX1Q1SnF6UXBMMWlueXJzUzdQVWdMVTAw/view?usp=sharing
3. An icon set sent by Melanie Wilberforce who has offered to create more of different sizes as requested: http://postimg.org/gallery/s1radxms/ 
4. The icon used by the similar Firefox extension, which the creator (Rob Grundy, as named on the Firefox extension page) has offered to share: https://addons.cdn.mozilla.net/user-media/addon_icons/595/595542-64.png?modified=1426709057
   Extension page: https://addons.mozilla.org/en-US/firefox/addon/gnu_terry_pratchett/
   If this is chosen, I would definitely not animate it like it is in the Firefox extension, though someone has suggested using a different pattern of lights if the header appears more than once in a page load.

I personally really like the lanterns and of those, I think I prefer option 3 (the various different sizes are quite well done, with a lot more detail in the larger ones but keeping it simple in the small ones). I do, however, really like the idea of keeping things uniform across browsers. The developer of the Firefox extension says he borrowed it himself (with permission) from the developers of an upcoming game (by 'Backspindle Games', who I'd obviously have to ask for permission from directly). I'd love some input from anyone who is interested and plans to use the extension. Which do you prefer, one of the lanterns or the light pattern?

I do feel I should reserve the right to make the final decision even if I disagree with the general public but I'd really like to see what others think. I'll also post this on the r/GNUTerryPratchett subreddit for a bit more public discussion. Cheers :)

**Comment by newfolder0** [comment]
I eventually went with Melanie's icons from option 3, though I might include an animated icon from option 4 in the drop down box that shows the clacks contents. Someone else suggested an option for users to choose which icon to use, that might be worth doing later.

**Pull request closed without merging**
