### PR TITLE
fix: update to Manifest v3

### LINKED ISSUE #13: Does not work on Mozilla.org
https://www.mozilla.org/ acts as though it does not have the header. I do not know enough of browsers/chrome to know why.

### LINKED ISSUE #14: This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.
I've just seen this message:
This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

Will the extension be updated to reflect the new terms, or is this a dead extension?

### PR DESCRIPTION
**Pull request by hmk**
This is a fix to make the extension continue to work with the new chrome store manifest change requirements.

Given that chrome is starting to break (see [this](https://www.reddit.com/r/discworld/comments/1g34hcz/chrome_just_updated_in_the_worst_possible_way/) reddit thread), there is some urgency to getting this updated.

fixes #14
fixes #13

### CODE REVIEW

**Comment by hmk** [comment]
this now properly displays the full clacks in the popup, same as before (no longer hotfix)

**Review by PorkDeCube — APPROVED** [review]

**Comment by newfolder0** [comment]
Thank you for your work.

Is there a reason you've included "webRequestBlocking" in the manifest permissions? I don't think there's a need for any blocking activity and I'd be hesitant to allow an extension that is effectively for novelty to have any blocking activity (bugs could stop the browser).

**Comment by newfolder0** [comment]
Actually when testing it in Chrome and installing from .zip file, it throws the error "'webRequestBlocking' requires manifest version of 2 or lower."

Removing this permissions item from the manifest seems to solve the issue without any impact on the functionality. I'll delete that and merge the pull request, then push the update to the Chrome Web Store.

Thank you again, I really appreciate your work!

Thank you for also adding the DEBUG code to print stuff to the console - that's a definite improvement.

Like I've said elsewhere, I don't work in web dev, no longer use Chrome and haven't written any software for 7+ years. The only reason I prefer to maintain final authority on PRs for this extension (the reason I don't hand over admin privileges to another contributor) is for security concerns. It has very powerful permissions that could easily be abused if the owner had malicious intent, so I feel some responsibility to the user base.

Cheers!

**Review by newfolder0 — APPROVED** [review]

**Review by newfolder0 — APPROVED** [review]
Approved with removal of WebRequestBlocking from the manifest. I have done it already.

**Comment by newfolder0** [comment]
Last step is to download the final package and upload it to the Chrome Web Store. I will do it now.

**Pull request merged**
